### ISSUE TITLE
Fails if your temp directory is on a different physical drive

### ISSUE THREAD

**Issue by natefinch** [natefinch/atomic#3]
The code currently writes a temp file in your temp dir and then tries to rename it over to the real filename.  However, this fails if your temp directory is on a different physical drive (this makes sense, there's no atomic way to actually transfer bytes from one disk to another).

Will require a fix to write the temp file to the same directory as the real file, with a unique name, and then rename.

**Comment by itchyny** [comment]
I agree with @heyimalex's comment, I think the code is correct and guarantees the temp file to be on the same directory (i.e. same drive).

**Comment by natefinch** [comment]
Ha, yes, thank you, I think this is an old bug that got fixed and then never closed.
