### ISSUE TITLE
[question]don't the atomic package need to call fsync?

### ISSUE THREAD

**Issue by lufia** [natefinch/atomic#5]
Hi, I'm reading this package.

Modern OSes probably has dirty buffer, so I think WriteFile needs to flush the buffer with `fsync` or `fdatasync`.
Windows might need to replace these syscalls with `FlushFileBuffers`.

**Comment by Al2Klimov** [comment]
Sure. See https://stackoverflow.com/a/15348491 . Stumbled over this as well, wondering why @natefinch didn’t have it already. But nevermind, I've opened PR #14 .
